// react-demo/src/components/MyButton.jsx
import React from 'react';

const my_button = (props) => {
    // This is jsx/react styling format.
    // It looks similar to CSS, but it is NOT CSS and can't be used in places where css is expected
    // Notice camelCased identifiers and quoted values which is NOT css (CSS == hyphen, no quotes)
    const local_style = {
        backgroundColor: "White",
        border: "2px solid blue",
        marginTop: "15px",
        cursor: "pointer",
        boxShadow: "2px 2px 2px",
    };

    return (
        <div>
            {/* This is JSX code, "onClick" is a special JSX event.
                A similar event being emitted by browser JS is "click" event */}
            <button style={local_style} onClick={props.click}>{props.label}</button>
        </div>
    );
};

export default my_button;

// vue-demo/src/components/MyButton.vue
<template>
    <div>
        <!-- v-on is listening for "click" event, it is
             the default JS event emitted by the browser -->
        <button class="local_style" v-on:click="click">{{label}}</button>
    </div>
</template>

<script>
    export default {
        name: "my-button",
        props: ['click', 'label'],
    }
</script>

<style scoped>
  /* This is normal css, can be re-used anywhere css is accepted */
  .local_style {
    background-color: White;
    border: 2px solid blue;
    margin-top: 15px;
    cursor: pointer;
    box-shadow: 2px 2px 2px;
  }
</style>
