// vue-demo/src/components/UserInput.vue
<template>
  <!-- As you can see here, we use normal html attribute "class",
       no need to use special JSX attribute "className" -->
  <div class="Card">
    <h3>What's your name</h3>

    <p>
      <input type="text"
             v-on:keyup="inputChanged"
             v-bind:value="name"/>
    </p>
  </div>
</template>

<script>
    export default {
        name: "user-input",
        props: ['inputChanged', 'name']
    }
</script>

<style scoped>

</style>

// react-demo/src/components/UserInput.jsx
import React from 'react';

const user_input = (props) => {
    return (
        <div className="Card">
            <h3>What's your name</h3>
            {/* This is JSX code, "onChange" is a special JSX event.
                A similar event being emitted by browser JS is "keyup" or "change" event */}
            <p>
                <input type="text"
                       onChange={props.inputChanged}
                       value={props.name}/>
            </p>
        </div>
    );
};

export default user_input;
